package com.enigma.x_food.constant;

public enum EActivity {
    CREATE_MERCHANT,
    UPDATE_MERCHANT,
    DELETE_MERCHANT,
    CREATE_BRANCH,
    UPDATE_BRANCH,
    DELETE_BRANCH,
    CREATE_PROMOTION,
    UPDATE_PROMOTION,
    DELETE_PROMOTION,
    APPROVE_CREATE_MERCHANT,
    APPROVE_DELETE_MERCHANT,
    REJECT_CREATE_MERCHANT,
    REJECT_DELETE_MERCHANT,
    APPROVE_CREATE_BRANCH,
    APPROVE_UPDATE_BRANCH,
    APPROVE_DELETE_BRANCH,
    REJECT_CREATE_BRANCH,
    REJECT_UPDATE_BRANCH,
    REJECT_DELETE_BRANCH,
    APPROVE_CREATE_PROMOTION,
    APPROVE_UPDATE_PROMOTION,
    APPROVE_DELETE_PROMOTION,
    REJECT_CREATE_PROMOTION,
    REJECT_UPDATE_PROMOTION,
    REJECT_DELETE_PROMOTION
}
