package com.enigma.x_food.constant;

public enum EActivity {
    CREATE_MERCHANT, UPDATE_MERCHANT, DELETE_MERCHANT,
    CREATE_BRANCH, UPDATE_BRANCH, DELETE_BRANCH,
    CREATE_PROMOTION, UPDATE_PROMOTION, DELETE_PROMOTION
}
